### PR TITLE
delete prompts

### PR DESCRIPTION
**Pull request by crapStone**

### CODE REVIEW

**Comment by 6543** [comment]
frontend build fail

**Review by Epsilon02 — DISMISSED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
it break `yarn start`

**Comment by 6543** [comment]
...
```
Error: src/app/onepager/onepager.component.html:30:7 - error NG8001: 'app-export-buttons' is not a known element:
1. If 'app-export-buttons' is an Angular component, then verify that it is part of this module.
2. If 'app-export-buttons' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

30       <app-export-buttons [docsTemplate]="DOCS_TEMPLATE"></app-export-buttons>
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/onepager/onepager.component.ts:7:16
    7   templateUrl: './onepager.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component OnePagerComponent.


Error: src/app/onepager/onepager.component.html:30:27 - error NG8002: Can't bind to 'docsTemplate' since it isn't a known property of 'app-export-buttons'.
1. If 'app-export-buttons' is an Angular component and it has 'docsTemplate' input, then verify that it is part of this module.
2. If 'app-export-buttons' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

30       <app-export-buttons [docsTemplate]="DOCS_TEMPLATE"></app-export-buttons>
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/onepager/onepager.component.ts:7:16
    7   templateUrl: './onepager.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component OnePagerComponent.
```
...

**Comment by Epsilon02** [comment]
Hmm this error is weird.
It should have nothin to do with this refactor 🤔
I will check it out later.

**Review by Epsilon02 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
fine now

**Pull request merged**
