### PR TITLE
Changed alterSnackbar to alert snackbar

### LINKED ISSUE #1083: Rename `altersnackbar` to `alertsnackbar`

### PR DESCRIPTION
**Pull request by DipayanP007**
Closes #1083 
* Changed alterSnackbar to alertsnackbar
* Changed alterSnackbar.model.ts, alterSnackbar.service.ts to alertSnackbar.model.ts, alertSnackbar.service.ts

### CODE REVIEW

**Comment by crapStone** [comment]
Thank you!

One small change request: could you please check in the deleted files after the rename. At the moment there are two versions of the same files with different names.

**Comment by 6543** [comment]
@DipayanP007 the majour problem with the old pull was, that binary files aka. images did differ (#1089)

this pull should be fine :)  - just delete the old files so they get marked as moved :+1:

**Comment by 6543** [comment]
@DipayanP007 sorry we just discovered it was not your fault - we fixed it with https://github.com/Calciumdibromid/CaBr2/pull/1091

**Comment by DipayanP007** [comment]
@6543 can you please explain the changes to be done? I will get it done then

**Comment by 6543** [comment]
`git rm frontend/src/app/@core/services/alertsnackbar/altersnackbar.*` & commit :)

**Comment by DipayanP007** [comment]
Hi @6543 I have made the changes and deleted the files

**Review by 6543 — APPROVED** [review]

**Review by crapStone — APPROVED** [review]

**Comment by 6543** [comment]
thanks for the pull :heart:

**Pull request merged**
